### ISSUE TITLE
Support for robolectric 3.1

### ISSUE THREAD

**Issue by fishmacs** [zbsz/robotest#12]
Currently robotest works ok with robolectric 3.0, but not with 3.1:

_**java.lang.NoSuchMethodError: org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.doNotAquireClass(Ljava/lang/String;)Lorg/robolectric/internal/bytecode/InstrumentationConfiguration$Builder;
[info]   at org.scalatest.RoboSuiteRunner.classLoaderConfig$lzycompute(RobolectricSuite.scala:140)
[info]   at org.scalatest.RoboSuiteRunner.classLoaderConfig(RobolectricSuite.scala:138)
[info]   at org.scalatest.RoboSuiteRunner.sdkEnvironment$lzycompute(RobolectricSuite.scala:149)
[info]   at org.scalatest.RoboSuiteRunner.sdkEnvironment(RobolectricSuite.scala:148)
[info]   at org.scalatest.RoboSuiteRunner.run(RobolectricSuite.scala:191)
[info]   at org.scalatest.RobolectricSuite$class.run(RobolectricSuite.scala:41)
...**_

I'm confused, seems org.robolectric.internal.bycode.InstrumentationConfiguration$Builder does have method doNotAquireClass in robolectric 3.1, why NoSuchMethodError?

**Comment by abhi-gadewar** [comment]
M Also facing same issue. Please provide resolution for this.
